#
# Compass Slaves MPUxxxx
#
obj-$(CONFIG_MPU_SENSORS_AMI304) += inv_mpu_ami30x.o
inv_mpu_ami30x-objs +=	ami30x.o

EXTRA_CFLAGS += -Idrivers/misc/inv_mpu
EXTRA_CFLAGS += -D__C99_DESIGNATED_INITIALIZER
